grails-app/domain/prueba1/Admin.groovy
package prueba1

class Admin extends User{
	int level
	double rating

	static hasMany = [forum:Forum]

	static constraints = {
		level nullable: false, range: 1..5
		rating nullable: false, range: 0..100
	}
}

grails-app/domain/prueba1/File.groovy
package prueba1

class File {

    String fileType
	Byte[]	content
	//long	 size

	static hasMany = [post:Post]

	static constraints = {
		fileType blank:false, nullable:false, matches:"[a-zA-Z]*/[a-zA-Z]*"
		content blank:false, nullable:false
		//size blank:false, nullable:false, max: 1310720
	}
	
	def download = {}
	def share = {}
}

grails-app/domain/prueba1/Regular.groovy
package prueba1

class Regular extends User{

    int postViews
	int strikesNumber
	int starsNumber

	static hasMany = [post:Post]
	
	static constraints = {
		postViews nullable:false, defaultValue: 0
		strikesNumber nullable:false, range: 0..3
		starsNumber nullable:false, range: 0..5
	}
}

grails-app/domain/prueba1/User.groovy
package prueba1

class User {

    String name
	String lastName
	int age
	String userName
	String password
	
	static constraints = {
		name blank: false, nullable: false, size:3..50
		lastName blank: false, nullable: false, size:3..50
		age blank: false, nullable: false, min: 13
		password blank: false, nullable: false, matches: "([a-zA-Z0-9]*[A-Z]+[a-zA-Z0-9]*[0-9]+[a-zA-Z0-9]*)|([a-zA-Z0-9]*[0-9]+[a-zA-Z0-9]*[A-Z]+[a-zA-Z0-9]*)", minSize: 8
		userName blank: false, nullable: false, unique:true
	}
}

grails-app/controllers/prueba1/AdminController.groovy
package prueba1

class AdminController {
	static scaffold=true
   // def index() { }
}

grails-app/controllers/prueba1/FileController.groovy
package prueba1

class FileController {
	static scaffold=true
    //def index() { }
}

grails-app/controllers/prueba1/ForumController.groovy
package prueba1

class ForumController {
	static scaffold=true
    //def index() { }
}

grails-app/controllers/prueba1/PostController.groovy
package prueba1

class PostController {
	static scaffold=true
    //def index() { }
}

grails-app/controllers/prueba1/RegularController.groovy
package prueba1

class RegularController {
	static scaffold=true
    //def index() { }
}

grails-app/controllers/prueba1/UserController.groovy
package prueba1

class UserController {
	static scaffold = true
    //def index() { }
}

grails-app/views/admin/_form.gsp
<%@ page import="prueba1.Admin" %>



<div class="fieldcontain ${hasErrors(bean: adminInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="admin.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" maxlength="50" required="" value="${adminInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: adminInstance, field: 'lastName', 'error')} required">
	<label for="lastName">
		<g:message code="admin.lastName.label" default="Last Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="lastName" maxlength="50" required="" value="${adminInstance?.lastName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: adminInstance, field: 'age', 'error')} required">
	<label for="age">
		<g:message code="admin.age.label" default="Age" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="age" type="number" min="13" value="${adminInstance.age}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: adminInstance, field: 'password', 'error')} required">
	<label for="password">
		<g:message code="admin.password.label" default="Password" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="password" pattern="${adminInstance.constraints.password.matches}" required="" value="${adminInstance?.password}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: adminInstance, field: 'userName', 'error')} required">
	<label for="userName">
		<g:message code="admin.userName.label" default="User Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="userName" required="" value="${adminInstance?.userName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: adminInstance, field: 'level', 'error')} required">
	<label for="level">
		<g:message code="admin.level.label" default="Level" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="level" from="${1..5}" class="range" required="" value="${fieldValue(bean: adminInstance, field: 'level')}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: adminInstance, field: 'rating', 'error')} required">
	<label for="rating">
		<g:message code="admin.rating.label" default="Rating" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="rating" from="${0..100}" class="range" required="" value="${fieldValue(bean: adminInstance, field: 'rating')}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: adminInstance, field: 'forum', 'error')} ">
	<label for="forum">
		<g:message code="admin.forum.label" default="Forum" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${adminInstance?.forum?}" var="f">
    <li><g:link controller="forum" action="show" id="${f.id}">${f?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="forum" action="create" params="['admin.id': adminInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'forum.label', default: 'Forum')])}</g:link>
</li>
</ul>


</div>

grails-app/views/admin/index.gsp
<%@ page import="prueba1.Admin" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'admin.label', default: 'Admin')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-admin" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-admin" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'admin.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="lastName" title="${message(code: 'admin.lastName.label', default: 'Last Name')}" />
					
						<g:sortableColumn property="age" title="${message(code: 'admin.age.label', default: 'Age')}" />
					
						<g:sortableColumn property="password" title="${message(code: 'admin.password.label', default: 'Password')}" />
					
						<g:sortableColumn property="userName" title="${message(code: 'admin.userName.label', default: 'User Name')}" />
					
						<g:sortableColumn property="level" title="${message(code: 'admin.level.label', default: 'Level')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${adminInstanceList}" status="i" var="adminInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${adminInstance.id}">${fieldValue(bean: adminInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: adminInstance, field: "lastName")}</td>
					
						<td>${fieldValue(bean: adminInstance, field: "age")}</td>
					
						<td>${fieldValue(bean: adminInstance, field: "password")}</td>
					
						<td>${fieldValue(bean: adminInstance, field: "userName")}</td>
					
						<td>${fieldValue(bean: adminInstance, field: "level")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${adminInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/file/index.gsp
<%@ page import="prueba1.File" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'file.label', default: 'File')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-file" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-file" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="fileType" title="${message(code: 'file.fileType.label', default: 'File Type')}" />
					
						<g:sortableColumn property="content" title="${message(code: 'file.content.label', default: 'Content')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${fileInstanceList}" status="i" var="fileInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${fileInstance.id}">${fieldValue(bean: fileInstance, field: "fileType")}</g:link></td>
					
						<td>${fieldValue(bean: fileInstance, field: "content")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${fileInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/forum/index.gsp
<%@ page import="prueba1.Forum" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'forum.label', default: 'Forum')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-forum" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-forum" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'forum.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="category" title="${message(code: 'forum.category.label', default: 'Category')}" />
					
						<th><g:message code="forum.admin.label" default="Admin" /></th>
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'forum.dateCreated.label', default: 'Date Created')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${forumInstanceList}" status="i" var="forumInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${forumInstance.id}">${fieldValue(bean: forumInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: forumInstance, field: "category")}</td>
					
						<td>${fieldValue(bean: forumInstance, field: "admin")}</td>
					
						<td><g:formatDate date="${forumInstance.dateCreated}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${forumInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/forum/show.gsp
<%@ page import="prueba1.Forum" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'forum.label', default: 'Forum')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-forum" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-forum" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list forum">
			
				<g:if test="${forumInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="forum.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${forumInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${forumInstance?.category}">
				<li class="fieldcontain">
					<span id="category-label" class="property-label"><g:message code="forum.category.label" default="Category" /></span>
					
						<span class="property-value" aria-labelledby="category-label"><g:fieldValue bean="${forumInstance}" field="category"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${forumInstance?.admin}">
				<li class="fieldcontain">
					<span id="admin-label" class="property-label"><g:message code="forum.admin.label" default="Admin" /></span>
					
						<span class="property-value" aria-labelledby="admin-label"><g:link controller="admin" action="show" id="${forumInstance?.admin?.id}">${forumInstance?.admin?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${forumInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="forum.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${forumInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${forumInstance?.post}">
				<li class="fieldcontain">
					<span id="post-label" class="property-label"><g:message code="forum.post.label" default="Post" /></span>
					
						<g:each in="${forumInstance.post}" var="p">
						<span class="property-value" aria-labelledby="post-label"><g:link controller="post" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:forumInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${forumInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/post/index.gsp
<%@ page import="prueba1.Post" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'post.label', default: 'Post')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-post" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-post" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="topic" title="${message(code: 'post.topic.label', default: 'Topic')}" />
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'post.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="lastUpdate" title="${message(code: 'post.lastUpdate.label', default: 'Last Update')}" />
					
						<g:sortableColumn property="itsAllowed" title="${message(code: 'post.itsAllowed.label', default: 'Its Allowed')}" />
					
						<th><g:message code="post.forum.label" default="Forum" /></th>
					
						<th><g:message code="post.regular.label" default="Regular" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${postInstanceList}" status="i" var="postInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${postInstance.id}">${fieldValue(bean: postInstance, field: "topic")}</g:link></td>
					
						<td><g:formatDate date="${postInstance.dateCreated}" /></td>
					
						<td><g:formatDate date="${postInstance.lastUpdate}" /></td>
					
						<td><g:formatBoolean boolean="${postInstance.itsAllowed}" /></td>
					
						<td>${fieldValue(bean: postInstance, field: "forum")}</td>
					
						<td>${fieldValue(bean: postInstance, field: "regular")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${postInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/post/show.gsp
<%@ page import="prueba1.Post" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'post.label', default: 'Post')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-post" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-post" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list post">
			
				<g:if test="${postInstance?.topic}">
				<li class="fieldcontain">
					<span id="topic-label" class="property-label"><g:message code="post.topic.label" default="Topic" /></span>
					
						<span class="property-value" aria-labelledby="topic-label"><g:fieldValue bean="${postInstance}" field="topic"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${postInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="post.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${postInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${postInstance?.lastUpdate}">
				<li class="fieldcontain">
					<span id="lastUpdate-label" class="property-label"><g:message code="post.lastUpdate.label" default="Last Update" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdate-label"><g:formatDate date="${postInstance?.lastUpdate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${postInstance?.itsAllowed}">
				<li class="fieldcontain">
					<span id="itsAllowed-label" class="property-label"><g:message code="post.itsAllowed.label" default="Its Allowed" /></span>
					
						<span class="property-value" aria-labelledby="itsAllowed-label"><g:formatBoolean boolean="${postInstance?.itsAllowed}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${postInstance?.forum}">
				<li class="fieldcontain">
					<span id="forum-label" class="property-label"><g:message code="post.forum.label" default="Forum" /></span>
					
						<span class="property-value" aria-labelledby="forum-label"><g:link controller="forum" action="show" id="${postInstance?.forum?.id}">${postInstance?.forum?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${postInstance?.regular}">
				<li class="fieldcontain">
					<span id="regular-label" class="property-label"><g:message code="post.regular.label" default="Regular" /></span>
					
						<span class="property-value" aria-labelledby="regular-label"><g:link controller="regular" action="show" id="${postInstance?.regular?.id}">${postInstance?.regular?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:postInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${postInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/regular/index.gsp
<%@ page import="prueba1.Regular" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'regular.label', default: 'Regular')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-regular" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-regular" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'regular.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="lastName" title="${message(code: 'regular.lastName.label', default: 'Last Name')}" />
					
						<g:sortableColumn property="age" title="${message(code: 'regular.age.label', default: 'Age')}" />
					
						<g:sortableColumn property="password" title="${message(code: 'regular.password.label', default: 'Password')}" />
					
						<g:sortableColumn property="userName" title="${message(code: 'regular.userName.label', default: 'User Name')}" />
					
						<g:sortableColumn property="postViews" title="${message(code: 'regular.postViews.label', default: 'Post Views')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${regularInstanceList}" status="i" var="regularInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${regularInstance.id}">${fieldValue(bean: regularInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: regularInstance, field: "lastName")}</td>
					
						<td>${fieldValue(bean: regularInstance, field: "age")}</td>
					
						<td>${fieldValue(bean: regularInstance, field: "password")}</td>
					
						<td>${fieldValue(bean: regularInstance, field: "userName")}</td>
					
						<td>${fieldValue(bean: regularInstance, field: "postViews")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${regularInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/user/index.gsp
<%@ page import="prueba1.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-user" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'user.name.label', default: 'Name')}" />
					
						<g:sortableColumn property="lastName" title="${message(code: 'user.lastName.label', default: 'Last Name')}" />
					
						<g:sortableColumn property="age" title="${message(code: 'user.age.label', default: 'Age')}" />
					
						<g:sortableColumn property="password" title="${message(code: 'user.password.label', default: 'Password')}" />
					
						<g:sortableColumn property="userName" title="${message(code: 'user.userName.label', default: 'User Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${userInstanceList}" status="i" var="userInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${userInstance.id}">${fieldValue(bean: userInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: userInstance, field: "lastName")}</td>
					
						<td>${fieldValue(bean: userInstance, field: "age")}</td>
					
						<td>${fieldValue(bean: userInstance, field: "password")}</td>
					
						<td>${fieldValue(bean: userInstance, field: "userName")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${userInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>